In [1]:
import numpy as np
import pandas as pd

In [27]:
a=np.arange(30,70).reshape(10,4)
a

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45],
       [46, 47, 48, 49],
       [50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65],
       [66, 67, 68, 69]])

In [29]:
np.sum(a,axis=0)#sum of  elements column wise


array([480, 490, 500, 510])

In [8]:
l1=[1,2,3,4,5,6,7,8,9,10]
np.sqrt(l1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [9]:
np.sum(a)

1980

In [30]:
np.sum(a,axis=1)

array([126, 142, 158, 174, 190, 206, 222, 238, 254, 270])

In [31]:
type(a)

numpy.ndarray

In [32]:
a.size

40

In [33]:
a.shape

(10, 4)

In [34]:
a.ndim

2

In [36]:
a=a.reshape(2,4,5)
a

array([[[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [37]:
a.ndim

3

In [38]:
a.dtype

dtype('int32')

In [39]:
np.sqrt(a)

array([[[5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189],
        [5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ],
        [6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958],
        [6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ]],

       [[7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923],
        [7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575],
        [7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ],
        [8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386]]])

In [41]:
a

array([[[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [46]:
a=np.arange(30,70).reshape(10,4)
a

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45],
       [46, 47, 48, 49],
       [50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65],
       [66, 67, 68, 69]])

In [47]:
a[2][1]

39

In [49]:
a[9][3]

69

In [50]:
a[1:2,1:3]

array([[35, 36]])

In [51]:
a[2]

array([38, 39, 40, 41])

In [53]:
a[:][2:3]

array([[38, 39, 40, 41]])

In [55]:
a[0:9][:]

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45],
       [46, 47, 48, 49],
       [50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65]])

In [56]:
a[0]

array([30, 31, 32, 33])

In [59]:
a[:][0:3]

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [61]:
a[0:3][:]

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [62]:
a[1:3,1:3]

array([[35, 36],
       [39, 40]])

In [63]:
np.vsplit(a,2)

[array([[30, 31, 32, 33],
        [34, 35, 36, 37],
        [38, 39, 40, 41],
        [42, 43, 44, 45],
        [46, 47, 48, 49]]),
 array([[50, 51, 52, 53],
        [54, 55, 56, 57],
        [58, 59, 60, 61],
        [62, 63, 64, 65],
        [66, 67, 68, 69]])]

In [64]:
np.hsplit(a,2)

[array([[30, 31],
        [34, 35],
        [38, 39],
        [42, 43],
        [46, 47],
        [50, 51],
        [54, 55],
        [58, 59],
        [62, 63],
        [66, 67]]),
 array([[32, 33],
        [36, 37],
        [40, 41],
        [44, 45],
        [48, 49],
        [52, 53],
        [56, 57],
        [60, 61],
        [64, 65],
        [68, 69]])]

In [66]:
s1=pd.Series(np.arange(10,30))
s1

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
11    21
12    22
13    23
14    24
15    25
16    26
17    27
18    28
19    29
dtype: int32

In [72]:
s1=pd.Series(np.arange(10,20), index=['a','b','c','d','e','f','g','h','i','j'])
s1

a    10
b    11
c    12
d    13
e    14
f    15
g    16
h    17
i    18
j    19
dtype: int32

In [73]:
s1[2]

12

In [74]:
s1[2:5]

c    12
d    13
e    14
dtype: int32

In [75]:
s1['h']

17

In [77]:
s1[3]

13

In [78]:
s1['d']

13

In [79]:
s1['a':'f']

a    10
b    11
c    12
d    13
e    14
f    15
dtype: int32

In [82]:
s1[0:5]

a    10
b    11
c    12
d    13
e    14
dtype: int32

In [83]:
np.arange(36).reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [89]:
A=pd.DataFrame(np.arange(36).reshape(6,6),index=['a','b','c','d','e','f'],columns=['col1','col2','col3','col4','col5','col6'])
A

col1  col2  col3  col4  col5  col6
a     0     1     2     3     4     5
b     6     7     8     9    10    11
c    12    13    14    15    16    17
d    18    19    20    21    22    23
e    24    25    26    27    28    29
f    30    31    32    33    34    35

In [86]:
type(A)

pandas.core.frame.DataFrame

In [90]:
A.loc['a','col1']

0

In [91]:
A.loc['d','col4']

21

In [92]:
A.iloc[0,0]

0

In [93]:
A.iloc[4,5]

29

In [95]:
A.loc[['e'],['col1','col2']]

col1  col2
e    24    25